##  CORRELATION ANALYSIS FOR SHARED PEAKS
##  Author: Claire LeBlanc
##  Last modified: 2022/8/18

##  Usage: Ran on shared peak files generated by interesecting .narrowPeak files
##  from nf-core/chipseq pipeline

##  For file paths to work, set working directory to the chip_seq_output folder
##  Folder should be organized with folders for each lineage, then folders for 
##  each transcription factor, and then folders for each cell type, which will 
##  contain the actual peak files

library(data.table)
library(readr)
library(ggplot2)
library(gridExtra)
library(cowplot)

theme_set(theme_cowplot())

#change this to be path to chip_seq_output folder
setwd("/Users/claireleblanc/summer_2022_research/chip_seq_output") 

#--------------------------Universal Data--------------------------------------#
#Get GPSeq data
GM06990 <- read.delim("GPSeq-data/GSE135882_Exp5/Exp5.rescaled.bins.size1000000.step100000.csm3.rmOutliers_chi2.rmAllOutliers.tsv", 
                      sep="\t")
GPSeq_data <- data.table(GM06990)
names(GPSeq_data) <- c("chrom","start","end","score","var")

#Get chromosome bins
bins <- read.delim("bins/hg19_bins_1e+06_1e+06_asGPSeq_no_offset.bed",
                   header=FALSE,sep='\t')
bins <- data.table(bins)
names(bins) <- c("bin_chr","bin_start","bin_end","name")

#--------------------------Functions--------------------------------------#
count_binned_sites_corr = function(path,zeros=FALSE){ 
  #get ChIP binding sites
  chip_bed <- read.delim(path,header=FALSE,sep='\t')
  sites <- data.table(chip_bed$V1, chip_bed$V2, chip_bed$V3)
  names(sites) <- c("chrom", "start","end")
  
  #Calculate the midpoint of each site
  sites[, mid:=(start+end)/2]
  
  #count the number of sites in each bin
  TFBS_binned <- sites[bins,on=.(mid>bin_start,mid<bin_end,chrom=bin_chr),nomatch = NULL]
  binned_counts <- TFBS_binned[,.N,by=.(mid,mid.1,chrom)]
  names(binned_counts) <- c("start","end","chrom","num")
  
  #Assign GPSeq Score to each bin
  GPSeq_counts <- GPSeq_data[binned_counts, on=.(start==start,end==end,chrom==chrom)]
  #nomatch removes all rows without a GPSeq score assigned
  
  GPSeq_counts <- GPSeq_counts[!is.na(score),]
  
  #Calculate the log GPSeq score
  GPSeq_counts[,logScore:=log2(score)]
  
  if (zeros){
    #For bins with no TFBS, set the number of sites equal to zero
    GPSeq_counts[is.na(num), num :=0]
  }
  else{
    #Remove sites with no TFBS
    GPSeq_counts <- GPSeq_counts[!is.na(num),] 
  }
  
  #normalize the number of sites to the total number of TFBS identified
  GPSeq_counts[,num_norm:=num/sum(num)]
  
  pearson <- cor.test(GPSeq_counts$logScore,GPSeq_counts$num, method = "pearson",exact=TRUE)
  pear_cor <- pearson$estimate
  pear_pval <- pearson$p.value
  spearman <- cor.test(GPSeq_counts$logScore,GPSeq_counts$num, method = "spearman",exact=TRUE)
  spear_cor <- spearman$estimate
  spear_pval <- spearman$p.value
  
  total <- sum(GPSeq_counts$num)
  split_path <- strsplit(path, "/")
  lineage <- split_path[[1]][1]
  TF <- split_path[[1]][2]
  cell <- split_path[[1]][3]
  rep <- strsplit(split_path[[1]][4],"_|\\.")[[1]][2]
  
  df <- c(pear_cor,pear_pval,spear_cor,spear_pval, total, lineage, TF, cell, rep)
  names(df) <- c("pearson","pearson pvalue","spearman","spearman pvalue","total", "lineage", "TF", "cell", "rep")
  
  return(df)
}


#changed all files to end in bed
filenames <- c("Myeloid/ELF4/K562/total_intersect.narrowPeak",
               "Myeloid/E2F4/K562/E2F4_intersect_peaks.narrowPeak",
               "Myeloid/Max/K562/total_intersect.bed",
               "Myeloid/NRF1/K562/total_intersect.bed",
               "Myeloid/TCF12/K562-exp1/total_intersect.narrowPeak",
               "Myeloid/TCF12/K562-exp2/total_intersect.narrowPeak",
               "Myeloid/TCF12/Kasumi/TCF12_intersect_peaks.narrowPeak",
               "Lymphoid/ATF4/Jurkat/cDNA_intersect.bed",
               "Lymphoid/FOXP1/SUDHL4/FOXP1_intersect.bed",
               "Lymphoid/FOXP1/RCK8/FOXP1_intersect_peaks.narrowPeak",
               "Lymphoid/GATA3/Jurkat/total_intersect.narrowPeak",
               "Lymphoid/GATA3/RPMI8402/total_intersect.narrowPeak",
               "Lymphoid/GATA3/thymocyte/total_intersect.narrowPeak",
               "Lymphoid/NFATC1/GM12878/total_intersect.narrowPeak",
               "Lymphoid/PRDM1/U266B1/total_intersect.narrowPeak")

#Calculate correlations
ndf <- lapply(filenames, count_binned_sites_corr)
df_coors <- data.frame(do.call(rbind,ndf))

#Set column types
df_coors$pearson <- as.numeric(df_coors$pearson)
df_coors$pearson.pvalue <- as.numeric(df_coors$pearson.pvalue)
df_coors$spearman.pvalue <- as.numeric(df_coors$spearman.pvalue)
df_coors$spearman <- as.numeric(df_coors$spearman)
df_coors$total <- as.numeric(df_coors$total)

df_table <- data.table(df_coors)
df_table[,n_reps:=(.N)-2, by=.(TF,cell)]
df_table[,n_reps:=paste("N = ",n_reps)]
df_table <- df_table[order(lineage)]

group.colors <- c("E2F4"="#008ae6","ELF4"="#1aa3ff","Max"="#4db8ff","NRF1"="#80ccff","TCF12"="#b3e0ff","ATF4"="#ff8000","FOXP1"="#ff9933","GATA3"="#ffb366","NFATC1"="#ffcc99","PRDM1"="#ffe6cc")

reps <- c("reps=2","reps=2","reps=1","reps=2","reps=2","reps=2","reps=2","reps=2","reps=2",
          "reps=1","reps=2","reps=2","reps=2","reps=1")
df_table[,n_reps:=reps]

#------------------------------Correlation Plotting----------------------------#

#Plot correlation for Lymphoid only, can change y to be spearman or pearson
lymph_coor <- ggplot(df_table[lineage=="Lymphoid",], 
                      aes(interaction(TF,cell),spearman,fill=TF)) +
  geom_bar(stat="identity") + 
  scale_fill_manual(values = group.colors[6:10]) +
  labs(fill = "Lymphoid TFs")+
  theme(legend.title = element_text(size=10,face="bold"),
        legend.text=element_text(size=8)) + 
  labs(x = "Transcription Factor", y = "Correlation Coefficient") + 
  theme(axis.title = element_text(size = 10, face = "bold"),
        plot.title = element_text(face = "bold",
                                  margin = margin(10, 0, 1, 0),
                                  size = 14),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0),
                                     size = 10),
        axis.line.x=element_blank(),
        axis.text = element_text(size=6)) +
  ylim(c(-0.05,1)) + 
  geom_hline(yintercept =0) +
  scale_x_discrete(labels=c("FOXP1.RCK8"="FOXP1\nRCK8",
                            "GATA3.RPMI8402"="GATA3\nRPMI8402",
                            "FOXP1.SUDHL4" = "FOXP1\nSUDHL4",
                            "GATA3.thymocyte"="GATA3\nthymocyte",
                            "PRDM1.U266B1"="PRDM1\nU266B1",
                            "NFATC1.GM12878" = "NFATC1\nGM12878", 
                            "ATF4.Jurkat" = "ATF4\nJurkat",
                            "GATA3.Jurkat" = "GATA3\nJurkat"),
                   limits=c("NFATC1.GM12878","ATF4.Jurkat",
                            "FOXP1.SUDHL4","GATA3.Jurkat",
                            "GATA3.thymocyte","PRDM1.U266B1",
                            "FOXP1.RCK8","GATA3.RPMI8402")) +
  geom_text(aes(label=paste("n=",total)), vjust=-0.7,size = 1.5)

#Get legend for lymphoid TFs
lymph_legend_coor <- get_legend(lymph_coor)   

#Plot correlation for myeloid TFs
my_coor <- ggplot(df_table[lineage=="Myeloid",], 
                      aes(interaction(TF,cell),spearman,fill=TF)) +
  geom_bar(stat="identity") + 
  scale_fill_manual(values = group.colors[1:5]) +
  labs(fill = "Myeloid TFs")+
  theme(legend.title = element_text(size=10,face="bold"),
        legend.text=element_text(size=8)) +
  labs(x = "Transcription Factor", y = "Pearson Correlation Coefficient") + 
  theme(axis.title = element_text(size = 10, face = "bold"),
        plot.title = element_text(face = "bold",
                                  margin = margin(10, 0, 1, 0),
                                  size = 14),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0),
                                     size = 10),
        axis.line.x=element_blank(),
        axis.text = element_text(size=6)) +
  ylim(c(-0.05,1)) + 
  geom_hline(yintercept =0) +
  scale_x_discrete(labels=c("ELF4.K562"="ELF4\nK562",
                            "Max.K562"="MAX\nK562",
                            "NRF1.K562"="NRF1\nK562",
                            "TCF12.K562-exp1"="TCF12\nK562",
                            "TCF12.K562-exp2"="TCF12\nK562",
                            "TCF12.Kasumi"="TCF12\nKasumi",
                            "E2F4.K562"="E2F4\nK562"),
                   limits=c("Max.K562",
                            "NRF1.K562", "TCF12.Kasumi",
                            "E2F4.K562","ELF4.K562",
                            "TCF12.K562-exp2","TCF12.K562-exp1")) + 
  geom_text(aes(label=paste("n=",total)), vjust=-0.7,size = 1.5) +
  geom_text(aes(label=n_reps), vjust=-2.2,size = 1.5)

#Get legend for myeloid TFs
my_legend_coor <- get_legend(my_coor)   

#manually set the number of reps in each experiment
reps <- c("reps=2","reps=2","reps=1","reps=2","reps=2","reps=2","reps=2","reps=2","reps=2",
          "reps=1","reps=2","reps=2","reps=2","reps=2","reps=1")
df_table[,n_reps:=reps]

#Plot correlation for all
all_no_legend <- ggplot(df_table, aes(interaction(TF,cell),pearson,fill=TF)) +
  geom_bar(stat="identity") + 
  labs(x = "Transcription Factor", y = "Pearson Correlation Coefficient") + 
  theme(axis.title = element_text(size = 10, face = "bold"),
        plot.title = element_text(face = "bold",
                                  margin = margin(10, 0, 1, 0),
                                  size = 14),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0),
                                     size = 10),
        axis.line.x=element_blank(),
        axis.text = element_text(size=6)) +
  ylim(c(-0.05,1)) + 
  geom_hline(yintercept =0) +
  scale_x_discrete(labels=c("ELF4.K562"="ELF4\nK562",
                            "Max.K562"="MAX\nK562",
                            "NRF1.K562"="NRF1\nK562",
                            "TCF12.K562-exp1"="TCF12\nK562",
                            "TCF12.K562-exp2"="TCF12\nK562",
                            "TCF12.Kasumi"="TCF12\nKasumi",
                            "FOXP1.RCK8"="FOXP1\nRCK8",
                            "GATA3.RPMI8402"="GATA3\nRPMI8402",
                            "FOXP1.SUDHL4" = "FOXP1\nSUDHL4",
                            "GATA3.thymocyte"="GATA3\nthymocyte",
                            "PRDM1.U266B1"="PRDM1\nU266B1",
                            "NFATC1.GM12878" = "NFATC1\nGM12878", 
                            "ATF4.Jurkat" = "ATF4\nJurkat",
                            "GATA3.Jurkat" = "GATA3\nJurkat",
                            "E2F4.K562"="E2F4\nK562"),
                   limits=c("Max.K562",
                            "NRF1.K562", "TCF12.Kasumi",
                            "E2F4.K562","ELF4.K562",
                            "TCF12.K562-exp2","TCF12.K562-exp1",
                            "NFATC1.GM12878","ATF4.Jurkat",
                            "FOXP1.SUDHL4","GATA3.Jurkat",
                            "GATA3.thymocyte","PRDM1.U266B1",
                            "FOXP1.RCK8","GATA3.RPMI8402")) + 
  theme(legend.position = "none") +
  scale_fill_manual(values=group.colors) + 
  geom_text(aes(label=paste("n=",total)), vjust=-0.7,size = 1.5) +
  geom_text(aes(label=n_reps), vjust=-2.2,size = 1.5)

#Adds legend to plot of all correlations
grid.arrange(all_no_legend,my_legend_coor,lymph_legend_coor,
             layout_matrix = rbind(c(1,1,1,1,NA),c(1,1,1,1,2),c(1,1,1,1,3),c(1,1,1,1,NA)))


#------------------------------Number of peaks Plotting------------------------#
#Plots num peaks vs. correlation
num_split_1 <- ggplot(df_intersect[lineage=="Lymphoid",], aes(total,spearman,color=TF))+
  geom_bar(stat="identity") + 
  scale_fill_manual(values = group.colors[6:10]) +
  labs(fill = "Lymphoid TFs")+
  theme(legend.title = element_text(size=10,face="bold"),
        legend.text=element_text(size=8))

num_legend_split_1 <- get_legend(ggp_split_1)   

num_split_2 <- ggplot(df_intersect[lineage=="Myeloid",], aes(total,spearman,color=TF))+
  geom_bar(stat="identity") + 
  scale_fill_manual(values = group.colors[1:5]) +
  labs(fill = "Myeloid TFs")+
  theme(legend.title = element_text(size=10,face="bold"),
        legend.text=element_text(size=8))

num_legend_split_2 <- get_legend(ggp_split_2) 

num_no_legend <- ggplot(df_table, aes(total,pearson,color=TF)) +
  geom_point() + 
  labs(x = "Number of peaks", y = "Pearson Correlation Coefficient",
       title = "Relationship between number of peaks and pearson correlation value",
       subtitle="Using peaks found in any rep of the experiment") + 
  theme(axis.title = element_text(size = 10, face = "bold"),
        plot.title = element_text(face = "bold",
                                  margin = margin(10, 0, 1, 0),
                                  size = 14),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0),
                                     size = 10),
        axis.line.x=element_blank(),
        axis.text = element_text(size=8)) +
  ylim(c(-0.05,1)) + 
  geom_hline(yintercept =0) +
  scale_color_manual(values=group.colors) +
  theme(legend.position = "none") 

grid.arrange(num_no_legend,num_legend_split_1,num_legend_split_2,
             layout_matrix = rbind(c(1,1,1,1,NA),c(1,1,1,1,2),c(1,1,1,1,3),c(1,1,1,1,NA)))