##  LAYER ANALYSIS FOR TOP SHARED PEAKS
##  Author: Claire LeBlanc
##  Last modified: 2022/8/18

##  Usage: Ran on top shared peak files generated by interesecting top 500 peaks
##  from .narrowPeak files from nf-core/chipseq pipeline

##  For file paths to work, set working directory to the chip_seq_output folder
##  Folder should be organized with folders for each lineage, then folders for 
##  each transcription factor, and then folders for each cell type, which will 
##  contain the actual peak files

#--------------------------Universal Data--------------------------------------#
library(data.table)
library(readr)
library(ggplot2)
library(gridExtra)
library(cowplot)

theme_set(theme_cowplot())

#change this to be path to chip_seq_output folder
setwd("/Users/claireleblanc/summer_2022_research/chip_seq_output") 

#--------------------------Universal Data--------------------------------------#
#Get GPSeq data
GM06990 <- read.delim("GPSeq-data/GSE135882_Exp5/Exp5.rescaled.bins.size1000000.step100000.csm3.rmOutliers_chi2.rmAllOutliers.tsv", 
                      sep="\t")
GPSeq_data <- data.table(GM06990)
names(GPSeq_data) <- c("chrom","start","end","score","var")

#Get chromosome bins
bins <- read.delim("bins/hg19_bins_1e+06_1e+06_asGPSeq_no_offset.bed",
                   header=FALSE,sep='\t')
bins <- data.table(bins)
names(bins) <- c("bin_chr","bin_start","bin_end","name")

#--------------------------Functions--------------------------------------#
count_sites_actual_binned = function(path,zeros=FALSE){ 
  #get ChIP binding sites
  chip_bed <- read.delim(path,header=FALSE,sep='\t')
  sites <- data.table(chip_bed$V1, chip_bed$V2, chip_bed$V3)
  names(sites) <- c("chrom", "start","end")
  
  #Calculate the midpoint of each site
  sites[, mid:=(start+end)/2]
  
  #count the number of sites in each bin
  TFBS_binned <- sites[bins,on=.(mid>bin_start,mid<bin_end,chrom=bin_chr),nomatch = NULL]
  binned_counts <- TFBS_binned[,.N,by=.(mid,mid.1,chrom)]
  names(binned_counts) <- c("start","end","chrom","num")
  
  #Assign GPSeq Score to each bin
  GPSeq_counts <- GPSeq_data[binned_counts, on=.(start==start,end==end,chrom==chrom)]
  #nomatch removes all rows without a GPSeq score assigned
  
  GPSeq_counts <- GPSeq_counts[!is.na(score),]
  
  #Calculate the log GPSeq score
  GPSeq_counts[,logScore:=log2(score)]
  
  if (zeros){
    #For bins with no TFBS, set the number of sites equal to zero
    GPSeq_counts[is.na(num), num :=0]
  }
  else{
    #Remove sites with no TFBS
    GPSeq_counts <- GPSeq_counts[!is.na(num)] 
  }
  
  #normalize the number of sites to the total number of TFBS identified
  GPSeq_counts[,num_norm:=num/sum(num)]
  
  return(GPSeq_counts)
}

get_layers = function(path=""){
  #create 10 layers (based on GPSeq score)
  layer <- seq(1:10)
  intervals <- seq(0,1.458131,length=11)
  layers <- data.table(layer,intervals[1:10],intervals[2:11])
  names(layers) <- c("layer", "start","end")
  GPSeq_data[,logScore:=log2(score)]
  
  #get bins per layer
  total_bins <- GPSeq_data[bins, on=.(start==bin_start,end==bin_end,chrom==bin_chr),nomatch=NULL]
  layer_bins <- total_bins[layers, on=.(logScore>start,logScore<end),nomatch=NULL]
  num_bins <- layer_bins[, .N, by=layer]
  
  #get counts of TFBS in each bin
  df <- count_sites_actual_binned(path, zeros=TRUE)
  
  #assign each bin to a layer based on the bins GPSeq score
  combined <- df[layers, on=.(logScore>start,logScore<end)]
  
  #count the number of bins and the total number of TFBS in each layer
  binned_counts <- combined[, .(sum(num, na.rm=TRUE)), by=layer]
  names(binned_counts) <- c("layer", "TFBS")
  
  
  #Normalized the number of TFBS by the total number of TFBS 
  #(to compare with experiments that got less overall peaks)
  binned_counts[,TFBS_n:=TFBS/sum(TFBS)]
  df_total_bins <- binned_counts[num_bins, on=.(layer==layer)]
  
  #Divide number of TFBS by the number of chromosome bins in that layer 
  #(to normalize for different amounts of DNA in each bin)
  normalized_bins <- df_total_bins[,normalized:=(TFBS_n/N)]
  
  #set type (for plotting multiple)
  split_path <- strsplit(path, "/")
  lineage <- split_path[[1]][1]
  TF <- split_path[[1]][2]
  cell <- split_path[[1]][3]
  rep <- strsplit(split_path[[1]][4],"_|\\.")[[1]][2]
  
  normalized_bins[,lineage:=lineage]
  normalized_bins[,TF:=TF]
  normalized_bins[,cell:=cell]
  normalized_bins[,rep:=rep]
  
  return(normalized_bins)
}

#changed all files to end in bed
filenames <- c("Myeloid/ELF4/K562/top_intersect_score.txt",
               "Myeloid/E2F4/K562/top_intersect_score.txt",
               "Myeloid/Max/K562/top_intersect_score.txt",
               "Myeloid/NRF1/K562/top_intersect_score.txt",
               "Myeloid/TCF12/K562-exp1/top_intersect_score.txt",
               #"Myeloid/TCF12/K562-exp2",pattern="top_intersect_score",
               "Myeloid/TCF12/Kasumi/top_intersect_score.txt",
               "Lymphoid/ATF4/Jurkat/cDNA-top_intersect_score.txt",
               "Lymphoid/FOXP1/SUDHL4/top_intersect_score.txt",
               "Lymphoid/FOXP1/RCK8/top_intersect_score.txt",
               "Lymphoid/GATA3/Jurkat/top_intersect_score.txt",
               "Lymphoid/GATA3/RPMI8402/top_intersect_score.txt",
               "Lymphoid/GATA3/thymocyte/top_intersect_score.txt",
               "Lymphoid/NFATC1/GM12878/top_intersect_score.txt",
               "Lymphoid/PRDM1/U266B1/top_intersect_score.txt")

ldf <- lapply(filenames, get_layers)
df_layers <- data.frame(do.call(rbind, ldf))

#Set column types
df_layers$layer <- as.factor(df_layers$layer)
dfl_c <- data.table(df_layers)

ndf <- lapply(filenames, count_binned_sites_corr)
df_coors <- data.frame(do.call(rbind,ndf))

group.colors <- c("E2F4"="#008ae6","ELF4"="#1aa3ff","Max"="#4db8ff","NRF1"="#80ccff","TCF12"="#b3e0ff","ATF4"="#ff8000","FOXP1"="#ff9933","GATA3"="#ffb366","NFATC1"="#ffcc99","PRDM1"="#ffe6cc")

reps <- c("reps=2","reps=2","reps=1","reps=2","reps=2","reps=2","reps=2","reps=2","reps=2",
          "reps=1","reps=2","reps=2","reps=2","reps=1")
df_table[,n_reps:=reps]

#------------------------------Layer Plotting----------------------------------#

layer_lymph <- ggplot(dfl_c [lineage=="Lymphoid",], aes(layer,normalized,group=interaction(TF,cell,rep),color=TF))+
  geom_point(size=1.5) + geom_line() + 
  labs(x = "Layer", y = element_blank()) +  
  scale_color_manual(values = group.colors[6:10]) +
  labs(fill = "Lymphoid TFs")+
  theme(legend.title = element_text(size=10,face="bold"),
        legend.text=element_text(size=8),
        plot.title = element_blank(), 
        axis.title = element_text(size = 10, face = "bold"),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())+ 
  ylim(0,.01)

layer_my<- ggplot(dfl_c[lineage=="Myeloid",], aes(layer,normalized,group=interaction(TF,cell,rep),color=TF))+
  geom_point(size=1.5) + geom_line() + 
  labs(x = "Layer", y = element_blank()) +  
  scale_color_manual(values = group.colors[1:5]) +
  labs(fill = "Myeloid TFs")+
  theme(legend.title = element_text(size=10,face="bold"),
        legend.text=element_text(size=8),
        plot.title = element_blank(), 
        axis.title = element_text(size = 10, face = "bold"),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) + 
  ylim(0,.01)

all_layer <- ggplot(dfl_c, aes(layer,normalized,group=interaction(TF,cell,rep),color=TF)) +
  geom_point(size=1.5) + geom_line() + 
  labs(x = "Layer", y = "Normalized number of TFBS") + 
  theme(axis.title = element_text(size = 10, face = "bold"),
        plot.title = element_text(margin = margin(10, 0, 1, 0),
                                  size = 14),
        plot.subtitle = element_text(margin = margin(0, 0, 10, 0),
                                     size = 10),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) + 
  scale_color_manual(values=group.colors) + 
  theme(legend.position = "none") +
  ylim(0,.01)

#Plot all three different layer plots together
grid.arrange(all_layer, layer_lymph,layer_my,
             layout_matrix = rbind(c(1,2),c(1,3)))

